# Generated by Django 3.2.4 on 2021-08-10 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210809_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='social_YouTube',
        ),
    ]
